// Generated by SimDock. Demo stimulus only; no functional assertions.
`timescale 1ns/1ps

module tb_counter;
    localparam int WIDTH = 8;

    logic clk;
    logic rst_n;
    logic enable;
    logic [WIDTH-1:0] count;

    counter #(
        .WIDTH(WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .count(count)
    );

    initial begin
        clk = '0;
        rst_n = 1'b0;
        enable = '0;
    end

    always #5.0 clk = ~clk;

    initial begin
        #50;
        @(negedge clk);
        rst_n = 1'b1;
    end

    // Add application-specific stimulus and checks here.
    initial begin
        #1000;
        $display("SimDock demo completed; no functional assertions.");
        $finish;
    end
endmodule
