// Generated by SimDock from saved input waveforms. No functional assertions.
`timescale 1ns/1ps

module tb_capture_dut;
    import capture_types::*;

    localparam WIDTH = 8;

    logic clk;
    logic rst_n;
    logic enable;
    logic valid;
    logic out_ready;
    logic [WIDTH-1:0] data;
    logic signed [7:0] signed_data;
    mode_t mode;
    logic [3:0] unknown_bus;
    logic ready;
    logic out_valid;
    logic [7:0] out_data;
    logic tx;

    capture_dut #(
        .WIDTH(WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .valid(valid),
        .out_ready(out_ready),
        .data(data),
        .signed_data(signed_data),
        .mode(mode),
        .unknown_bus(unknown_bus),
        .ready(ready),
        .out_valid(out_valid),
        .out_data(out_data),
        .tx(tx)
    );

    // Graphical stimulus: generated from saved Tickx input waveforms.
    initial clk = 1'b0;
    always #(10000 * 1ps) clk = ~clk;
    initial begin : drive_rst_n
        rst_n = 1'h0;
        #(100000 * 1ps);
        rst_n = 1'h1;
    end
    initial begin : drive_enable
        enable = 1'h0;
        #(250000 * 1ps);
        enable = 1'h1;
        #(250000 * 1ps);
        enable = 1'bx;
        #(250000 * 1ps);
        enable = 1'bz;
    end
    initial begin : drive_valid
        valid = 1'h0;
        #(250000 * 1ps);
        valid = 1'h1;
        #(500000 * 1ps);
        valid = 1'h0;
    end
    initial begin : drive_out_ready
        out_ready = 1'h1;
        #(500000 * 1ps);
        out_ready = 1'h0;
        #(250000 * 1ps);
        out_ready = 1'h1;
    end
    initial begin : drive_data
        data = 8'h0;
        #(250000 * 1ps);
        data = 8'ha5;
        #(250000 * 1ps);
        data = 8'h5a;
        #(250000 * 1ps);
        data = 8'bxx10zz01;
    end
    initial begin : drive_signed_data
        signed_data = 8'hff;
        #(250000 * 1ps);
        signed_data = 8'bxxxxx10z;
        #(250000 * 1ps);
        signed_data = 8'h7;
        #(250000 * 1ps);
        signed_data = 8'bxxxxxxxx;
    end
    initial begin : drive_mode
        mode = mode_t'(2'h0);
        #(250000 * 1ps);
        mode = mode_t'(2'h1);
        #(250000 * 1ps);
        mode = mode_t'(2'h2);
        #(250000 * 1ps);
        mode = mode_t'(2'h0);
    end
    initial begin : drive_unknown_bus
        unknown_bus = 4'bxxxx;
        #(250000 * 1ps);
        unknown_bus = 4'bzzzz;
        #(250000 * 1ps);
        unknown_bus = 4'bx10z;
        #(250000 * 1ps);
        unknown_bus = 4'ha;
    end
    longint unsigned __simdock_duration_ns;
    initial begin
        if (!$value$plusargs("SIMDOCK_DURATION_NS=%d", __simdock_duration_ns))
            __simdock_duration_ns = 2000;
        #(__simdock_duration_ns);
        $display("SimDock demo completed; no functional assertions.");
        $finish;
    end
endmodule
