set(STAGE3_PROTOTYPE "${CMAKE_CURRENT_LIST_DIR}")
function(stage3_isolate_tests)
    foreach(target regmap_gui_tests regmap_core_tests regmap_cli_tests regmap_suiteapp_integration_test)
        if(TARGET ${target})
            target_sources(${target} PRIVATE "${STAGE3_PROTOTYPE}/profile.cpp")
        endif()
    endforeach()
    target_compile_definitions(regmap_gui_tests PRIVATE PILOT_UI_INITIALIZATION)
    set_property(TARGET regmap_gui_tests PROPERTY SOURCES "${STAGE3_PROTOTYPE}/gui_smoke_tests.cpp;${STAGE3_PROTOTYPE}/profile.cpp")
    target_compile_definitions(regmap_gui_tests PRIVATE REGMAP_EXPECTED_VERSION="${RegMapWorkbench_VERSION}")
endfunction()
cmake_language(DEFER CALL stage3_isolate_tests)
