// Generated by SimDock. Selected scoreboard checks are enabled.
`timescale 1ns/1ps

module tb_capture_dut;
    import capture_types::*;

    localparam WIDTH = 8;

    logic clk;
    logic rst_n;
    logic enable;
    logic valid;
    logic out_ready;
    logic [WIDTH-1:0] data;
    logic signed [7:0] signed_data;
    mode_t mode;
    logic [3:0] unknown_bus;
    logic ready;
    logic out_valid;
    logic [7:0] out_data;
    logic tx;

    capture_dut #(
        .WIDTH(WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .valid(valid),
        .out_ready(out_ready),
        .data(data),
        .signed_data(signed_data),
        .mode(mode),
        .unknown_bus(unknown_bus),
        .ready(ready),
        .out_valid(out_valid),
        .out_data(out_data),
        .tx(tx)
    );

    // Graphical stimulus: generated from saved Tickx input waveforms.
    initial clk = 1'b0;
    always #(10000 * 1ps) clk = ~clk;
    initial begin : drive_rst_n
        rst_n = 1'h0;
        #(100000 * 1ps);
        rst_n = 1'h1;
    end
    initial begin : drive_enable
        enable = 1'h0;
        #(250000 * 1ps);
        enable = 1'h1;
        #(250000 * 1ps);
        enable = 1'bx;
        #(250000 * 1ps);
        enable = 1'bz;
    end
    initial begin : drive_valid
        valid = 1'h0;
        #(250000 * 1ps);
        valid = 1'h1;
        #(500000 * 1ps);
        valid = 1'h0;
    end
    initial begin : drive_out_ready
        out_ready = 1'h1;
        #(500000 * 1ps);
        out_ready = 1'h0;
        #(250000 * 1ps);
        out_ready = 1'h1;
    end
    initial begin : drive_data
        data = 8'h0;
        #(250000 * 1ps);
        data = 8'ha5;
        #(250000 * 1ps);
        data = 8'h5a;
        #(250000 * 1ps);
        data = 8'bxx10zz01;
    end
    initial begin : drive_signed_data
        signed_data = 8'hff;
        #(250000 * 1ps);
        signed_data = 8'bxxxxx10z;
        #(250000 * 1ps);
        signed_data = 8'h7;
        #(250000 * 1ps);
        signed_data = 8'bxxxxxxxx;
    end
    initial begin : drive_mode
        mode = mode_t'(2'h0);
        #(250000 * 1ps);
        mode = mode_t'(2'h1);
        #(250000 * 1ps);
        mode = mode_t'(2'h2);
        #(250000 * 1ps);
        mode = mode_t'(2'h0);
    end
    initial begin : drive_unknown_bus
        unknown_bus = 4'bxxxx;
        #(250000 * 1ps);
        unknown_bus = 4'bzzzz;
        #(250000 * 1ps);
        unknown_bus = 4'bx10z;
        #(250000 * 1ps);
        unknown_bus = 4'ha;
    end

    // SimDock scoreboard: expected behavior comes from the selected check plan.
    if (1) begin : __simdock_scoreboard
        typedef struct {
            logic [8-1:0] data;
            realtime accepted_at;
            bit expired;
        } expected_item;
        expected_item pending[$];
        integer errors = 0, compared = 0, accepted = 0, received = 0, discarded = 0;
        bit done = 0, decoding = 0, initialized = 0;
        wire in_reset = (rst_n !== 1'b1);
        localparam realtime TIMEOUT_NS = 250000;
        localparam bit CHECK_DATA = 1, CHECK_COUNT = 1;
        localparam bit CHECK_FORMAT = 1, CHECK_TIMEOUT = 1;

        clocking sample @(posedge clk);
            default input #1step;
            input in_data = data;
            input in_valid = valid;
            input in_ready = ready;

        endclocking

        task automatic report_error(input string reason);
            errors++;
            if (errors <= 100) $display("SIMDOCK_CHECK_FAIL time=%0t %s", $time, reason);
            else if (errors == 101) $display("SIMDOCK_CHECK_FAIL Further errors are counted in the final summary.");
        endtask
        task automatic expect_value(input logic [8-1:0] value);
            expected_item item;
            accepted++;
            if (pending.size() >= 4096) begin
                report_error("More than 4096 outstanding items; check the interface bindings or run a smaller case.");
                return;
            end
            if (CHECK_DATA && $isunknown(value)) report_error("Accepted input contains X/Z.");
            item.data = value;
            item.accepted_at = $realtime;
            item.expired = 0;
            pending.push_back(item);
        endtask
        task automatic observe_value(input logic [8-1:0] value);
            expected_item item;
            received++;
            if (pending.size() == 0) begin
                if (CHECK_COUNT || CHECK_DATA)
                    report_error($sformatf("Unexpected output #%0d: actual=0x%0h", received, value));
                return;
            end
            item = pending.pop_front();
            compared++;
            if (CHECK_TIMEOUT && !item.expired && $realtime - item.accepted_at > TIMEOUT_NS)
                report_error("Output arrived after its deadline.");
            if (CHECK_DATA && value !== item.data)
                report_error($sformatf("Item #%0d: expected=0x%0h actual=0x%0h", compared, item.data, value));
        endtask
        task automatic finish_check();
            if (done) return;
            if (compared == 0)
                report_error("No transactions were compared. Check the stimulus, bindings and run duration.");
            if (CHECK_COUNT && pending.size() != 0)
                report_error($sformatf("Missing outputs: %0d expected item(s) remain.", pending.size()));
            if (decoding) report_error("Simulation ended in the middle of a UART frame.");
            done = 1;
            if (errors == 0)
                $display("SIMDOCK_CHECK_PASS compared=%0d accepted=%0d received=%0d reset_discarded=%0d", compared, accepted, received, discarded);
            else
                $display("SIMDOCK_CHECK_FAILED errors=%0d compared=%0d accepted=%0d received=%0d reset_discarded=%0d", errors, compared, accepted, received, discarded);
        endtask

        // Reset is observed asynchronously, including pulses shorter than a clock.
        always @(posedge in_reset) begin
            if (1) begin
                discarded += pending.size();
                pending.delete();
            end
        end
        always @(sample) begin
            if (!done && !in_reset) begin
                if (sample.in_valid === 1'b1 && sample.in_ready === 1'b1) expect_value(sample.in_data[7:0]);

                if (CHECK_TIMEOUT) begin
                    foreach (pending[i]) begin
                        if (!pending[i].expired && $realtime - pending[i].accepted_at > TIMEOUT_NS) begin
                            report_error($sformatf("Output timed out for expected value 0x%0h.", pending[i].data));
                            pending[i].expired = 1;
                        end
                    end
                end
            end
        end

        localparam realtime BIT_NS = 1000000000.0 / 10000000;
        task automatic decode_frame();
            logic [8-1:0] value;
            logic parity_bit;
            value = '0;
            #(BIT_NS / 2.0);
            if (tx !== 1'b0) begin
                if (CHECK_FORMAT) report_error("Invalid UART start bit.");
                return;
            end
            for (int bit_index = 0; bit_index < 8; bit_index++) begin
                #(BIT_NS);
                value[bit_index] = tx;
            end
            if (0 != 0) begin
                #(BIT_NS);
                parity_bit = ^value;
                if (0 == 2) parity_bit = ~parity_bit;
                if (CHECK_FORMAT && tx !== parity_bit)
                    report_error("UART parity mismatch.");
            end
            #(BIT_NS);
            // Check each half-bit center of the configured stop interval.
            for (int half_bit = 0; half_bit < 2 - 1; half_bit++) begin
                if (half_bit != 0) #(BIT_NS / 2.0);
                if (CHECK_FORMAT && tx !== 1'b1)
                    report_error("Invalid or shortened UART stop bit.");
            end
            #(BIT_NS / 2.0 - 0.001);
            observe_value(value);
        endtask
        initial begin
            forever begin
                @(negedge tx);
                if (!done && !in_reset && tx === 1'b0) begin
                    decoding = 1;
                    fork : frame_or_reset
                        decode_frame();
                        begin wait (in_reset || done); end
                    join_any
                    disable frame_or_reset;
                    decoding = 0;
                end
            end
        end

    end
    longint unsigned __simdock_duration_ns;
    initial begin
        if (!$value$plusargs("SIMDOCK_DURATION_NS=%d", __simdock_duration_ns))
            __simdock_duration_ns = 2000;
        #(__simdock_duration_ns);
        __simdock_scoreboard.finish_check();
        $finish;
    end
endmodule
