#include <iostream>
#include <string>

int main(int argc, char** argv)
{
    std::cout << "// DESCRIPTION: Generated by ZeroSlack's portable "
                 "Verilator includer\n";
    for (int index = 1; index < argc; ++index) {
        const std::string argument = argv[index];
        if (argument.rfind("-D", 0) == 0) {
            const std::size_t separator = argument.find('=', 2);
            if (separator != std::string::npos) {
                std::cout << "#define "
                          << argument.substr(2, separator - 2)
                          << ' ' << argument.substr(separator + 1) << '\n';
                continue;
            }
        }
        std::cout << "#include \"" << argument << "\"\n";
    }
    return 0;
}
