add_library(zeroslack_cli_support STATIC src/cli/zeroslackcli.cpp src/cli/zeroslackcli.h)
target_include_directories(zeroslack_cli_support PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src/cli")
target_link_libraries(zeroslack_cli_support PUBLIC Qt6::Core PRIVATE ZeroSlack::Semantic)
if(SuiteApp_FOUND)
    target_link_libraries(zeroslack_cli_support PRIVATE SuiteApp::suiteapp)
    target_compile_definitions(zeroslack_cli_support PRIVATE ZEROSLACK_CLI_HAS_SUITEAPP=1)
endif()
add_executable(zeroslack_cli src/cli/zeroslackclimain.cpp)
set_target_properties(zeroslack_cli PROPERTIES OUTPUT_NAME "zeroslack-cli")
target_include_directories(zeroslack_cli PRIVATE "${ZEROSLACK_GENERATED_INCLUDE_DIR}")
target_link_libraries(zeroslack_cli PRIVATE zeroslack_cli_support)
