# Domain ownership is explicit. Only include/zeroslack is a public interface.
set(ZEROSLACK_SEMANTIC_SOURCES
    include/zeroslack/semantic/effectivevalueservice.h
    include/zeroslack/semantic/fsmgraphservice.h
    include/zeroslack/semantic/hierarchyservice.h
    include/zeroslack/semantic/incrementalsemanticanalysisworker.h
    include/zeroslack/semantic/moduleblockdiagramservice.h
    include/zeroslack/semantic/pinloomcodelinkstore.h
    include/zeroslack/semantic/projectsnapshot.h
    include/zeroslack/semantic/relationshipanalysisworker.h
    include/zeroslack/semantic/relationshipservice.h
    include/zeroslack/semantic/rtlinsightlink.h
    include/zeroslack/semantic/semanticanalysisinput.h
    include/zeroslack/semantic/semanticanalysisrequest.h
    include/zeroslack/semantic/semanticanalysisresult.h
    include/zeroslack/semantic/semanticapi.h
    include/zeroslack/semantic/semanticdependencygraph.h
    include/zeroslack/semantic/semanticdiffservice.h
    include/zeroslack/semantic/semanticindex.h
    include/zeroslack/semantic/semanticindexsnapshot.h
    include/zeroslack/semantic/semanticsharddirectory.h
    include/zeroslack/semantic/semanticsourcerange.h
    include/zeroslack/semantic/semanticstableidentity.h
    include/zeroslack/semantic/signaljourneyservice.h
    include/zeroslack/semantic/slangmanager.h
    include/zeroslack/semantic/smartrelationshipbuilder.h
    include/zeroslack/semantic/statetransitiongraphservice.h
    include/zeroslack/semantic/statetransitiontriggerservice.h
    include/zeroslack/semantic/suitecontextcatalog.h
    include/zeroslack/semantic/symbolpresentationservice.h
    include/zeroslack/semantic/symbolrelationshipengine.h
    include/zeroslack/semantic/symbolsemanticmetadata.h
    include/zeroslack/semantic/symboltaxonomy.h
    include/zeroslack/semantic/workspaceconfigurationservice.h
    src/analysis/incrementalanalysisplanservice.cpp
    src/analysis/incrementalanalysisplanservice.h
    src/analysis/incrementalsemanticanalysisworker.cpp
    src/editor/triviapositionmap.cpp
    src/editor/triviapositionmap.h
    src/insights/fsmgraphservice.cpp
    src/insights/moduleblockdiagramservice.cpp
    src/insights/statetransitiongraphservice.cpp
    src/insights/statetransitiontriggerservice.cpp
    src/integrations/pinloom/pinloomcodelinkstore.cpp
    src/integrations/suite/suitecontextcatalog.cpp
    src/semantic/effectivevalueservice.cpp
    src/semantic/hierarchyservice.cpp
    src/semantic/hierarchyservicetraversal.cpp
    src/semantic/projectsnapshot.cpp
    src/semantic/relationshipanalysisworker.cpp
    src/semantic/relationshipservice.cpp
    src/semantic/relationshipserviceordering.cpp
    src/semantic/relationshipserviceordering.h
    src/semantic/semanticanalysisinput.cpp
    src/semantic/semanticanalysisrequest.cpp
    src/semantic/semanticchangeclassifier.cpp
    src/semantic/semanticchangeclassifier.h
    src/semantic/semanticdependencygraph.cpp
    src/semantic/semanticdiffservice.cpp
    src/semantic/semanticindex.cpp
    src/semantic/semanticindexcompletion.cpp
    src/semantic/semanticindexcompletioncontext.cpp
    src/semantic/semanticindexcompletiontypequeries.cpp
    src/semantic/semanticindexlookup.cpp
    src/semantic/semanticindexlookuphelpers.cpp
    src/semantic/semanticindexlookuphelpers.h
    src/semantic/semanticindexmodulecontext.cpp
    src/semantic/semanticindexmodulecontexthelpers.cpp
    src/semantic/semanticindexmodulecontexthelpers.h
    src/semantic/semanticindexrelationships.cpp
    src/semantic/semanticindexsnapshot.cpp
    src/semantic/semanticindexsnapshotpublication.cpp
    src/semantic/semanticindexsnapshotqueries.cpp
    src/semantic/semanticindexstore.cpp
    src/semantic/semanticsourceremap.cpp
    src/semantic/semanticsourceremap.h
    src/semantic/semanticstableidentity.cpp
    src/semantic/signaljourneyservice.cpp
    src/semantic/slangcompilationcontext.cpp
    src/semantic/slangmanagerdiagnostics.cpp
    src/semantic/slangmanagerrelationships.cpp
    src/semantic/slangmanagersymbols.cpp
    src/semantic/slangpreprocessorfacts.cpp
    src/semantic/slangpreprocessorfacts.h
    src/semantic/slangrelationshiphelpers.cpp
    src/semantic/slangrelationshiphelpers.h
    src/semantic/slangsymbolcollector.cpp
    src/semantic/slangsymbolcollector.h
    src/semantic/slangsymbolcollectorhelpers.cpp
    src/semantic/slangsymbolcollectorhelpers.h
    src/semantic/slangsymbolpresentation.cpp
    src/semantic/slangsymbolpresentation.h
    src/semantic/smartrelationshipbuilder.cpp
    src/semantic/smartrelationshipbuilderanalysis.cpp
    src/semantic/smartrelationshipbuildercontext.cpp
    src/semantic/smartrelationshipbuildertiming.cpp
    src/semantic/symbolanalyzerworkspace.cpp
    src/semantic/symbolanalyzerworkspace.h
    src/semantic/symbolpresentationservice.cpp
    src/semantic/symbolrelationshipengine.cpp
    src/semantic/symbolrelationshipqueries.cpp
    src/semantic/symboltaxonomy.cpp
    src/settings/workspaceconfigurationservice.cpp
)
set(ZEROSLACK_DOCUMENT_SOURCES
    include/zeroslack/documents/crashrecoveryservice.h
    include/zeroslack/documents/documentbuffer.h
    include/zeroslack/documents/documentchange.h
    include/zeroslack/documents/documentsapi.h
    include/zeroslack/documents/documentsnapshot.h
    include/zeroslack/documents/editorfileidentity.h
    include/zeroslack/documents/tsdocument.h
    src/documents/crashrecoveryservice.cpp
    src/documents/documentbuffer.cpp
    src/editor/editorfileidentity.cpp
    src/editor/tsdocument.cpp
)
